#!/bin/sh
# To make the application more portable we extract the script PATH and the script name
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
echo $SCRIPT_PATH
echo $SCRIPT_NAME
cd "$SCRIPT_PATH"
python3 run.py